# MOD LOADER SETTINGS
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

# Additional links and logo:
# logoFile = "logo.png"
# displayURL = "https://example.com"
# issueTrackerURL = "https://github.com/user/repo/issues"

# CORE MOD METADATA
[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

# DEPENDENCIES: MINECRAFT
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

# DEPENDENCIES: FORGE
[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

# DEPENDENCIES: REMEDY CORE (API)
[[dependencies."${mod_id}"]]
    modId = "remedy_core"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"